### ISSUE TITLE
Maven build failing

### ISSUE THREAD

**Issue by miparnisari** [aws-cloudformation/aws-cloudformation-resource-providers-codegurureviewer#10]
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codegurureviewer/blob/ee75cde516bf44ebaf5ae215f96a1d675a1597b8/buildspec.yml#L9-L15

Your CodeBuild config is not building anything. Please change this to something like: 

```
  build:
    commands:
      - pre-commit run --all-files
      - |
        for directory in $CODEBUILD_SRC_DIR/aws-*; do
          cd "$directory"
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify
        done
```

**Comment by PatMyron** [comment]
**failing due to `aws-cloudformation-rpdk-java-plugin` upgrade issues:**

[`cannot find symbol: method writeResponse`](https://sage.amazon.com/posts/961045)

https://w.amazon.com/bin/view/AWS21/Design/Uluru/V2/Upgrade_Guide

**Comment by xxz-dev** [comment]
fixed in https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codegurureviewer/pull/24
